# Generated by Django 5.0.3 on 2024-04-29 10:16

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to=documents.models.custom_upload_to)),
                ('is_have_form', models.BooleanField(default=False)),
            ],
        ),
    ]
