# Generated by Django 5.0.3 on 2024-05-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_usersdocuments_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdocuments',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
