# Generated by Django 5.0.3 on 2024-05-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_usersdocuments_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdocuments',
            name='approved',
            field=models.BooleanField(default=None),
        ),
    ]
