# Generated by Django 5.0.3 on 2024-05-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_usersdocuments_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdocuments',
            name='is_approved',
            field=models.IntegerField(default=-1),
        ),
    ]
